name: scraping news
on: 
  schedule:
  - cron: '0 * * * *'
jobs:
  scraping:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome:3.141.59-vanadium
        ports:
          - 4444:4444
        volumes:
          - /dev/shm:/dev/shm
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.5'
    - name: Scraping News
      env:
        URL: "https://www.pref.miyazaki.lg.jp/kenko/hoken/kansensho/covid19/hassei.html"
        SELENIUM_HOST: localhost
        TZ: Asia/Tokyo
      run: |
        gem install bundler
        bundle update --bundler
        bundle install
        ruby scraping.rb
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v2
      with:
        commit-message: 'Update news.json'
        branch: news
        base: master
        # labels: auto_merge
        branch-suffix: timestamp
        title: '最新のお知らせ更新'
        body: '公式サイトのお知らせが更新されました。差分を確認してマージしてください。'
    # ここから下はお知らせに差分があった場合のみ実行する
    - uses: actions/checkout@v2
      if: steps.cpr.outputs.pr_number != 0
    - name: Scraping Data
      env:
        URL: "https://www.pref.miyazaki.lg.jp/kenko/hoken/kansensho/covid19/hassei.html"
        SELENIUM_HOST: localhost
        TZ: Asia/Tokyo
      run: |
        ruby scraping_data.rb
      if: steps.cpr.outputs.pr_number != 0
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        commit-message: 'Update data.json'
        branch: data
        base: master
        # labels: auto_merge
        branch-suffix: timestamp
        title: '陽性患者数更新'
        body: '公式サイトの情報が更新されました。差分を確認してマージしてください。'
      if: steps.cpr.outputs.pr_number != 0
